import React, { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  Search,
  FileText,
  FileDown,
  X,
} from "lucide-react";
import { api } from "../services/api";

interface Incident {
  id: number;
  incident_uid: string;
  timestamp: string;
  severity: string;
  system: string;
  status: string;
  root_cause: string;
  suggested_fix: string;
  resolution_notes?: string;
}

export default function Incidents() {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [loading, setLoading] = useState(true);

  // Resolution modal state
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(
    null,
  );
  const [newStatus, setNewStatus] = useState("Resolved");
  const [notes, setNotes] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Export report state
  const [exportedText, setExportedText] = useState("");
  const [showExportModal, setShowExportModal] = useState(false);

  const fetchIncidents = async (showLoading = true) => {
    if (showLoading) setLoading(true);
    try {
      const res = await api.get("/incidents/");
      setIncidents(res.data);
    } catch (err) {
      console.error("Failed to fetch incidents:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    let ignore = false;

    async function loadIncidents() {
      try {
        const res = await api.get("/incidents/");
        if (!ignore) {
          setIncidents(res.data);
        }
      } catch (err) {
        console.error("Failed to fetch incidents:", err);
      } finally {
        if (!ignore) {
          setLoading(false);
        }
      }
    }

    void loadIncidents();

    return () => {
      ignore = true;
    };
  }, []);

  const filteredIncidents = useMemo(() => {
    let result = incidents;

    if (statusFilter !== "All") {
      result = result.filter((i) => i.status === statusFilter);
    }

    if (search.trim()) {
      const query = search.toLowerCase();
      result = result.filter(
        (i) =>
          i.incident_uid.toLowerCase().includes(query) ||
          i.system.toLowerCase().includes(query) ||
          i.root_cause.toLowerCase().includes(query),
      );
    }

    return result;
  }, [search, statusFilter, incidents]);

  const handleUpdateStatus = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedIncident) return;
    setSubmitting(true);
    try {
      await api.put(
        `/incidents/${selectedIncident.id}/status?status=${newStatus}&resolution_notes=${encodeURIComponent(notes)}`,
      );
      setSelectedIncident(null);
      setNotes("");
      fetchIncidents();
    } catch (err) {
      console.error("Failed to update incident status:", err);
      alert("Error updating status.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleExportIncident = async (incident: Incident) => {
    try {
      const res = await api.get(`/incidents/${incident.id}/export`);
      const data = res.data;

      const report = `=====================================================
            INCIDENT DETAILS POST-MORTEM REPORT
=====================================================
Ticket UID:     ${data.incident_uid}
Severity:       ${data.severity.toUpperCase()}
Target System:  ${data.system}
Log Timestamp:  ${data.timestamp}
Current Status: ${data.status.toUpperCase()}

-----------------------------------------------------
IDENTIFIED ROOT CAUSE:
-----------------------------------------------------
${data.root_cause}

-----------------------------------------------------
RECOMMENDED FIXES / ACTIONABLE REMEDIATIONS:
-----------------------------------------------------
${data.suggested_fix}

-----------------------------------------------------
RESOLUTION SUMMARY NOTES:
-----------------------------------------------------
${data.resolution_notes || "No resolution post-mortem comments recorded yet."}

=====================================================
Report generated by DevOps Copilot v1.0.0
=====================================================`;

      setExportedText(report);
      setShowExportModal(true);
    } catch (err) {
      console.error("Failed to export incident details:", err);
      alert("Failed to generate incident export report.");
    }
  };

  const severityColors: Record<string, string> = {
    Critical: "bg-rose-500/10 text-rose-400 border-rose-500/25 text-glow-rose",
    High: "bg-orange-500/10 text-orange-400 border-orange-500/25",
    Medium: "bg-amber-500/10 text-amber-400 border-amber-500/25",
    Low: "bg-slate-500/10 text-slate-400 border-slate-500/25",
  };

  const statusColors: Record<string, string> = {
    Open: "bg-rose-500/10 text-rose-400 border-rose-500/15 animate-pulse",
    Investigating: "bg-cyan-500/10 text-cyan-400 border-cyan-500/15",
    Resolved: "bg-emerald-500/10 text-emerald-400 border-emerald-500/15",
    Closed: "bg-slate-500/10 text-slate-400 border-slate-500/15",
  };

  return (
    <div className="space-y-6">
      {/* Search and Filters Bar */}
      <div className="glass-card p-4 rounded-2xl border border-white/5 flex flex-col md:flex-row justify-between gap-4">
        {/* Search */}
        <div className="relative flex-1">
          <Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-500" />
          <input
            type="text"
            className="w-full pl-10 pr-4 py-2 glass-input text-xs"
            placeholder="Search tickets by ID, system namespace, or faults..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>

        {/* Status Filter tabs */}
        <div className="flex gap-2">
          {["All", "Open", "Investigating", "Resolved", "Closed"].map((tab) => (
            <button
              key={tab}
              onClick={() => setStatusFilter(tab)}
              className={`px-4 py-2 rounded-lg border text-xs font-semibold transition-all cursor-pointer ${
                statusFilter === tab
                  ? "bg-indigo-600/15 border-indigo-500/35 text-indigo-300"
                  : "bg-white/2 border-white/5 text-slate-400 hover:text-slate-300"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Incident Tickets List */}
      <div className="glass-card rounded-2xl border border-white/5 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="bg-white/[0.02] text-xs font-semibold text-slate-400 uppercase tracking-wider border-b border-white/5">
              <tr>
                <th className="px-6 py-4">Ticket ID</th>
                <th className="px-6 py-4">System</th>
                <th className="px-6 py-4">Severity</th>
                <th className="px-6 py-4">Root Cause Context</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {loading ? (
                <tr>
                  <td
                    colSpan={6}
                    className="px-6 py-8 text-center text-slate-500 font-mono text-xs"
                  >
                    Loading incident tracking repository...
                  </td>
                </tr>
              ) : filteredIncidents.length === 0 ? (
                <tr>
                  <td
                    colSpan={6}
                    className="px-6 py-8 text-center text-slate-500 font-mono text-xs"
                  >
                    No matching incidents found.
                  </td>
                </tr>
              ) : (
                filteredIncidents.map((incident) => (
                  <tr
                    key={incident.id}
                    className="hover:bg-white/[0.005] transition-colors"
                  >
                    <td className="px-6 py-4 font-mono font-bold text-xs text-indigo-400">
                      {incident.incident_uid}
                    </td>
                    <td className="px-6 py-4 font-semibold text-slate-300">
                      {incident.system}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`px-2 py-0.5 rounded border text-[10px] font-mono uppercase tracking-wider ${severityColors[incident.severity] || severityColors.Medium}`}
                      >
                        {incident.severity}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-xs text-slate-400 max-w-md truncate">
                      {incident.root_cause}
                    </td>
                    <td className="px-6 py-4">
                      <span
                        className={`px-2 py-0.5 rounded border text-[10px] font-semibold uppercase tracking-wider ${statusColors[incident.status]}`}
                      >
                        {incident.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex justify-end gap-2.5">
                        <button
                          onClick={() => setSelectedIncident(incident)}
                          className="px-3 py-1.5 bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 hover:text-white hover:bg-indigo-500/25 rounded-md text-xs font-semibold transition-colors cursor-pointer"
                        >
                          Resolve
                        </button>
                        <button
                          onClick={() => handleExportIncident(incident)}
                          className="p-1.5 bg-white/3 border border-white/5 text-slate-400 hover:text-white rounded-md hover:bg-white/5 transition-colors cursor-pointer"
                          title="Export Incident Report"
                        >
                          <FileDown className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Resolve / Manage Incident Modal Overlay */}
      {selectedIncident && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4">
          <div className="w-full max-w-lg glass-card rounded-2xl p-6 border border-white/10 relative">
            <button
              onClick={() => setSelectedIncident(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
            <h3 className="font-outfit font-extrabold text-lg text-slate-100 mb-6 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-400" />
              <span>Manage Incident {selectedIncident.incident_uid}</span>
            </h3>

            <form
              onSubmit={handleUpdateStatus}
              className="space-y-4 text-xs font-semibold"
            >
              <div>
                <label className="block text-slate-400 uppercase tracking-wider mb-2">
                  Update Ticket Status
                </label>
                <select
                  className="w-full py-2.5 px-3 glass-input text-xs cursor-pointer font-sans"
                  value={newStatus}
                  onChange={(e) => setNewStatus(e.target.value)}
                >
                  <option value="Open" className="bg-slate-900 text-slate-200">
                    Open
                  </option>
                  <option
                    value="Investigating"
                    className="bg-slate-900 text-slate-200"
                  >
                    Investigating
                  </option>
                  <option
                    value="Resolved"
                    className="bg-slate-900 text-slate-200"
                  >
                    Resolved
                  </option>
                  <option
                    value="Closed"
                    className="bg-slate-900 text-slate-200"
                  >
                    Closed
                  </option>
                </select>
              </div>

              <div>
                <label className="block text-slate-400 uppercase tracking-wider mb-2">
                  Resolution Post-Mortem Notes
                </label>
                <textarea
                  required={newStatus === "Resolved" || newStatus === "Closed"}
                  placeholder="Describe resolution steps, fixed tags, app_offline deployments or configuration patches..."
                  className="w-full h-28 py-2.5 px-3 glass-input text-xs font-sans font-normal leading-relaxed"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-white/5 font-medium">
                <button
                  type="button"
                  onClick={() => setSelectedIncident(null)}
                  className="px-4 py-2 bg-white/2 hover:bg-white/5 border border-white/5 rounded-lg text-slate-400 hover:text-white transition-colors cursor-pointer text-xs"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="px-4 py-2 bg-gradient-to-r from-indigo-600 to-cyan-500 hover:from-indigo-500 hover:to-cyan-400 text-white rounded-lg transition-colors cursor-pointer glow-btn text-xs disabled:opacity-50"
                >
                  {submitting ? "Updating..." : "Save Changes"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Export Report View Modal Overlay */}
      {showExportModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4">
          <div className="w-full max-w-2xl glass-card rounded-2xl p-6 border border-white/10 relative">
            <button
              onClick={() => setShowExportModal(false)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
            <h3 className="font-outfit font-extrabold text-lg text-slate-100 mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-400" />
              <span>Incident Detail Report</span>
            </h3>

            <div className="bg-slate-950 p-4 rounded-xl border border-white/5 font-mono text-xs max-h-96 overflow-y-auto leading-relaxed text-slate-300 select-all whitespace-pre">
              {exportedText}
            </div>

            <div className="flex justify-end pt-4 mt-4 border-t border-white/5">
              <button
                onClick={() => setShowExportModal(false)}
                className="px-4 py-2 bg-gradient-to-r from-indigo-600 to-cyan-500 hover:from-indigo-500 hover:to-cyan-400 text-white rounded-lg transition-colors cursor-pointer text-xs font-semibold"
              >
                Close Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
